- name: message-1
  ansible.builtin.debug:
    msg: "message from msg-1"

- name: message-2
  ansible.builtinff.debug:
    msg: "message from msg-2"

- name: message-3
  ansible.builtin.debug:
    msg: "message from msg-3"